/* Main.ino file generated by New Project wizard
 *
 * Created:   mer dic 3 2014
 * Processor: ATmega328P
 * Compiler:  Arduino AVR
 */
#include "MotorDrive.h"

MotorDrive motor(3,4,A0);

void mostrar(String texto, int valor){
   Serial.print(texto);
   Serial.print(": ");
   Serial.println(valor);
}
void setup()
 { // put your setup code here, to run once:
 motor.begin();
 Serial.begin(9600);
 }

void loop()
 { // put your main code here, to run repeatedly:
 
   motor.runClockwise(200);
   mostrar("runClockwise", motor.getCurrentSpeed());
   delay(2000);
   
   motor.pause();
   mostrar("pause", motor.getCurrentSpeed());
   delay(1000);
   
   motor.runAntiClockwise(motor.getCurrentSpeed(), true);
   mostrar("runAntiClockwise", motor.getCurrentSpeed());
   delay(2000);
   
   motor.pause();
   mostrar("pause", motor.getCurrentSpeed());
   delay(1000);

   motor.resume();
   mostrar("resume", motor.getCurrentSpeed());
   delay(2000);

   motor.stop();
   mostrar("stop", motor.getCurrentSpeed());
   delay(1000);
 }
